export const SET_STREET = 'SET_STREET'
export const SET_SELECT_STREET_ID = 'SET_SELECT_STREET_ID'
export const SET_SELECT_STREET_NAME = 'SET_SELECT_STREET_NAME'

export const SET_HOUSE = 'SET_HOUSE'
export const SET_SELECT_HOUSE_ID = 'SET_SELECT_HOUSE_ID'
export const SET_SELECT_HOUSE_NAME = 'SET_SELECT_HOUSE_NAME'

export const SET_APARTAMENT = 'SET_APARTAMENT'
export const SET_SELECT_APARTAMENT_ID = 'SET_SELECT_APARTAMENT_ID'
export const SET_SELECT_APARTAMENT_NUM = 'SET_SELECT_APARTAMENT_NUM'

export const SET_CLIENTS = 'SET_CLIENTS'
export const SET_CLIENT_ID = 'SET_CLIENT_ID'
export const SET_CLIENT_PHONE_NUM = 'SET_CLIENT_PHONE_NUM'